version: 2

sources:
  - name: tdf_source # Nom que vous utiliserez dans dbt pour appeler ce groupe
    database: tdf2026 # Votre Project ID BigQuery
    schema: TDF_dataset # Votre Dataset BigQuery
    description: "Données brutes du Tour de France importées dans BigQuery"
    tables:
      - name: cash_price
        description: "Table contenant les prix et primes"
      
      - name: rider_information
        description: "Informations sur les coureurs"
        
      - name: rider_results
        description: "Résultats individuels des coureurs"
        
      - name: stage_information
        description: "Détails sur les étapes"
        
      - name: stage_results
        description: "Résultats par étape"

      - name: all_stage_information_with_type
        description: "Table enrichie contenant les informations de chaque étape avec le type associé"